variables:
  DOCKER_HOST: tcp://docker:2375/
stages:
  - build
  - test
  - package

build:
  stage: build
  image: node:16.13.1-alpine
  before_script:
    - npm install
  script:
    - npm run build

test:
  stage: test
  image: node:16.13.1-alpine
  before_script:
    - npm install
  script:
    - npm run test

package:
  stage: package
  image: docker:18-git
  services:
    - name: docker:18-dind
  variables:
    DOCKER_REGISTRY_NAME: $MY_CI_REGISTRY_NAME:$CI_PIPELINE_ID
  script:
    - docker login -u $MY_CI_DOCKER_USER --password $MY_CI_DOCKER_PASS
    - docker build -t $DOCKER_REGISTRY_NAME $CI_PROJECT_DIR
    - docker push $DOCKER_REGISTRY_NAME

