apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  project: default
  source:
    repoURL: git@gitlab.com:todo32/deployment-artifacts.git
    path: todo-frontend/prod
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
